version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        # This env command will take the clientID, redirectURL, and client
        # secret and then add it to the runtime variables. More info on AWS docs
        # https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html
        - env | grep -e GOOGLE_CLIENT_ID -e GOOGLE_CLIENT_SECRET -e NEXTAUTH_SECRET >> .env.production
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
